import { TFieldData } from "../Common/TFieldData";

export type TIIFCOKYC = {
  propFullName: { value: string; warning: boolean };
  ProposerDob: { value: Date | null | string; warning: boolean };
  relatesPersonFullName: { value: string; warning: boolean };
  gender: { value: string; warning: false };
  verificationDoc: { value: string; warning: boolean };
  verificationDocNumber: { value: string; warning: boolean };
  verificationDocFile: { name: string; value: string; warning: boolean };
  addressDoc: { value: string; warning: boolean };
  addressDocNumber: { value: string; warning: boolean };
  addressDocFile: { name: string; value: string; warning: boolean };
  relationshipBetweenProps: { value: string; warning: boolean };
  custImage: { value: string; warning: boolean; name: string };
  pinCode: { value: string; warning: boolean };
  houseNUmber: { value: string; warning: boolean };
  city: { value: string; warning: boolean };
  state: { value: string; warning: boolean };
  customertype: { value: string; warning: boolean };
  docID: { value: string; warning: boolean };
};

export type TIIFCOKYCRESPONSE = {
  OFF_TEL_NUM: string;
  RESI_TEL_NUM: string;
  kycAadhaar: string;
  kycAddress1: string;
  kycAddress2: string;
  kycAddress3: string;
  kycCity: string;
  kycCountry: string;
  kycCustomerName: string;
  kycDOB: string;
  kycDistrict: string;
  kycEmail: string;
  kycFirstName: string;
  kycID: string;
  kycLastName: string;
  kycMiddleName: string;
  kycMobile: string;
  kycNo: string;
  kycPAN: string;
  kycPincode: string;
  kycState: string;
  kycgender: string;
};

export type TVerifyCKYCForm = {
  ckyc_option: 1 | 2;
  full_name: TFieldData;
  dob: TFieldData;
  doc_type: TFieldData;
  doc_id: TFieldData;
  customer_type: TFieldData;
  gender: TFieldData;
  form_sixety: TFieldData;
  pincode: TFieldData;
  city: TFieldData;
  houseNo: TFieldData;
  area_town: TFieldData;
  income_source: TFieldData;
  Family_relationship: TFieldData;
  Occupation: TFieldData;
  imageFormSixetyName: TFieldData;
  passport: TFieldData;
  identity_doc: TFieldData;
  family_full_name: TFieldData;
  mobile: TFieldData;
  email: TFieldData;
  toggle_switch: boolean;
  pep_remark: string;
  section: string;
};
// export type TPepForm = {
//   toggle_switch: boolean;
//   pep_remark: string;
// };

export type TManualCKYCForm = {
  email?: any;
  full_name: TFieldData;
  dob: TFieldData;
  doc_type_id_proof: TFieldData;
  doc_no_id_proof: TFieldData;
  doc_id_proof_image: TFieldData;
  customer_type: TFieldData;
  gender: TFieldData;
  doc_type_address_proof: TFieldData;
  doc_address_proof_image: TFieldData;

  doc_address_id_proof?: TFieldData;
  relatedPersonName?: TFieldData;
  relationshipType?: TFieldData;
  photoDocument?: TFieldData;
  kycPincode?: TFieldData;
  addressPHouse?: TFieldData;
  addressPCity?: TFieldData;
  addressPState?: TFieldData;
};

export type TCKYCDetails = {
  transactionId: string;
  kycTranNumber: string;
  kycNo: string;
  kycCustomerName: string;
  kycFirstName: string;
  kycMiddleName: string;
  kycLastName: string;
  kycDOB: string;
  kycMobile: string;
  kycEmail: string;
  kycPAN: string;
  kycAadhaar: string;
  kycAddress1: string;
  kycAddress2: string;
  kycAddress3: string;
  kycCity: string;
  kycDistrict: string;
  kycState: string;
  kycPincode: string;
  CkycPTransaction: string;
  zone: string;
  poaStatus: string;
  poiStatus: string;
  kycStatus: string;
  kycManualURL: string;
  ncb_tag: string;
  correspondencePincode: string;
  kyc_details: any;
  data?: any;
  message?: string;
  success?: boolean;
  responseCode?: string;
  responseMessage?: string;
  firstName?: string;
  middleName?: string;
  lastName?: string;
  signzyAppId?: string;
  merchantId?: string;
  journeyType?: string;
  AadharNumber: string;
  Address: string;
  AddressType: string;
  BeatCode: string;
  BusinessObjectId: string;
  CKYCNo: string;
  City: string;
  Country: string;
  Creator: string;
  CustomerGSTINNo: string;
  CustomerId: string;
  CustomerNumber: string;
  CustomerType: string;
  DateOfBirth: string;
  District: string;
  Email: string;
  EncryptedAadharNumber: string;
  EncryptedPanNumber: string;
  FirstName: string;
  Gender: string;
  IdNumber: string;
  IdType: string;
  InsertBy: string;
  InsertTime: string;
  IsHandicappedMod: string;
  JourneyType: string;
  LastName: string;
  MaritalStatusCode: string;
  MerchantId: string;
  MiddleName: string;
  Mobile: string;
  OccupationType: string;
  PANNumber: string;
  PANStatusCode: string;
  PartyStatus: string;
  PinSINo: string;
  PostCode: string;
  State: string;
  Title: string;
  TrackingNo: string;
  TempData: {
    "Mask-IdNumber": string;
    "MaskAfter-IdNumber": string;
    "Mask-Mobile": string;
    "MaskAfter-Mobile": string;
  };
  CorporateName: string;
  DateOfRegistration: string;
};

export type TCKYC = {
  VERIFY_KYC_FORM: TVerifyCKYCForm;
  MANUAL_KYC_THIRD_PARTY_URL: string;
  CKYC_DETAILS: TCKYCDetails;
  MANUAL_KYC_STATUS: boolean;
};

export type TStarManualCKYCForm = {
  full_name: TFieldData;
  dob: TFieldData;
  doc_type: TFieldData;
  doc_id: TFieldData;
  customer_type: TFieldData;
  gender: TFieldData;
  pincode: TFieldData;
  city: TFieldData;
  houseNo: TFieldData;
  area_town: TFieldData;
  income_source: TFieldData;
  Family_relationship: TFieldData;
  Occupation: TFieldData;
  imageFormSixetyName: TFieldData;
  passport: TFieldData;
  identity_doc: TFieldData;
  family_full_name: TFieldData;
  toggle_switch: boolean;
  pep_remark: string;
  pan_card: TFieldData;
};

export type TCignaManualCKYCForm = {
  kycCusName: TFieldData;
  dobForKyc: TFieldData;
  idenDocNameForKyc: TFieldData;
  identityDocument: TFieldData;
  docAddNameForKyc: TFieldData;
  addDocument: TFieldData;
  formsixty: TFieldData;
  formsixtyNoForKyc: TFieldData;
  customerPhoto: TFieldData;
  customer_type: TFieldData;
};

export type TIffcoManualCKYCForm = {
  cusType: TFieldData;
  genderForKyc: TFieldData;
  kycCusName: TFieldData;
  dobForKyc: TFieldData;
  relatedPersonName: TFieldData;
  docNameForKyc: TFieldData;
  docNameForKyc1: TFieldData;
  docIDNoForKyc: TFieldData;
  docIDNoForKyc1: TFieldData;
  docNameForKyc2: TFieldData;
  docIDNoForKyc2: TFieldData;
  relationshipType: TFieldData;
  kycPincode: TFieldData;
  addressPHouse: TFieldData;
  addressPCity: TFieldData;
  addressPState: TFieldData;
  otherDocNameForKyc: TFieldData;
  otherDocIDNoForKyc: TFieldData;
  document: TFieldData;
  otherDocument: TFieldData;
  photoDocument: TFieldData;
};
