export type TTermPlanType =
  | "PURE_LIFE_COVER"
  | "INCOME_REPLACEMENT"
  | "RETURN_OF_PREMIUM"
  | "WHOLE_LIFE";

export enum ETermPlanType {
  PURE_LIFE_COVER = "PURE_LIFE_COVER",
  INCOME_REPLACEMENT = "INCOME_REPLACEMENT",
  RETURN_OF_PREMIUM = "RETURN_OF_PREMIUM",
  WHOLE_LIFE = "WHOLE_LIFE",
}
