import { TCashlessGarage } from "../Common/TCashlessGarage";

export type TCarPremiumDetails = {
  includeDriverCover: number;
  version: "v1" | "v2";
  withDiscountroadSideAssistance: number;
  withDiscountinvoicePriceCover: number;
  withDiscountdepreciationCover: number;
  withDiscountconsumablesCover: number;
  withOutBasicOd: number;
  withOutBundleAccessory: number;
  withBundleAccessory: number;
  paymentId: string;
  pTransactionId: string;
  tata_coral_plan_amount: number;
  tata_gold_plan_amount: number;
  tata_perl_plan_amount: number;
  tata_perlplus_plan_amount: number;
  tata_sapphire_plan_amount: number;
  tata_sapphirep_plan_amount: number;
  tata_sapphirepp_plan_amount: number;
  zerodepAssurePlusPremiume: number;
  zerodepAssurePremiume: number;
  includedkeyReplacementCover: number;
  correlationId: string;
  error: boolean;
  freeRoadSideAssistance: 0 | 1;
  tyreSecureCover: number;
  exshowroomPrice: number;
  minimumIDV: number;
  maximumIDV: number;
  IDV: number;
  basicOD: number;
  basicTP: number;
  netPremium: number;
  ncbDiscount: number;
  odDiscount: number;
  antiTheftDiscount: number;
  associationDiscount: number;
  ePolicyDiscount: number;
  otherDiscount: number;
  deductibleDiscount: number;
  ambulanceChargesCover: number;
  consumablesCover: number;
  depreciationCover: number;
  hospitalCashCover: number;
  hydrostaticLockCover: number;
  keyReplacementCover: number;
  paOwnerDriver: number;
  includedPAOwnerDriver: 0 | 1;
  engineGearBoxProtection: number;
  noClaimBonusSameSlab: number;
  roadSideAssistance: number;
  medicalExpenses: number;
  accessoryCoverCharge: number;
  llDriver: number;
  paFamily: number;
  invoicePriceCover: number;
  driverCover: number;
  fg_plan_type: string;
  tariffDiscount: number;
  seatingCapacity: number;
  cngKitOD: number;
  cngKitTP: number;
  passerngerCover: number;
  personalBelonging: number;
  includedPersonalBelonging: 0 | 1;
  GD_ProPlanPremium: number;
  GD_DProPlanPremium: number;
  GD_DCProPlanPremium: number;
  GD_DCEProPlanPremium: number;
  GD_DCTProPlanPremium: number;
  GD_DCETProPlanPremium: number;
  GD_DCRTIProPlanPremium: number;
  GD_DCERTIProPlanPremium: number;
  GD_DCTRTIProPlanPremium: number;
  GD_DCETRTIProPlanPremium: number;
  UniqueRequestID: string;
  RSQUOTEID: any;
  GD_ProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
  };
  GD_DProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
  };
  GD_DCProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
    consumable: number;
  };
  GD_DCEProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
    consumable: number;
    engine: number;
  };
  GD_DCERTIProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
    consumable: number;
    engine: number;
    invoice: number;
  };
  GD_DCTProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
    consumable: number;
    tyre: number;
  };
  GD_DCTRTIProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
    consumable: number;
    tyre: number;
    invoice: number;
  };
  GD_DCETProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
    consumable: number;
    engine: number;
    tyre: number;
  };
  GD_DCETRTIProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
    consumable: number;
    engine: number;
    tyre: number;
    invoice: number;
  };
  GD_DCRTIProPlan: {
    personalbelonging: number;
    roadside: number;
    Key: number;
    zerodeps: number;
    consumable: number;
    invoice: number;
  };
  withOutBundlebBasicOd: number;
  withBundleBasicOD: number;
  withOutNcbDiscount: number;
  withBundleNcbDiscount: number;
};

export type TCarSingleQuoteDetail = {
  premiumDetails: TCarPremiumDetails;
  productDetails: {
    id: number;
    product_name: string;
    brochure: string;
    product_code: string;
    rate_calc_method: string;
    proposal_method: string;
    tax_calc_method: string;
    discount_calc_method: string;
    rating: number;
    product_desc: string;
    buy_online_code: string;
    policy_covers: string;
    company_product_map: {
      company_code: string;
    };
  };
  CompanyDetails: {
    company_code: string;
    name: string;
    short_desc: string;
    logo: string;
    claim_ratio: string;
  };
  cashlessGarageLists: Array<TCashlessGarage>;
};
